server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course-v2
    username: postgres
    password: banco123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always
  rabbitmq:
    addresses: amqps://pvkzowfr:MlVr8MMxhLPfv5PfGm3PkGAzYv4mK8Lg@shark.rmq.cloudamqp.com/pvkzowfr


logging:
  level:
    com.ead: TRACE
    root: info
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser'
  broker:
    exchange:
      userEvent: ead.userevent
    queue:
      userEventQueue:
        name: ead.userevent.ms.course

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health